name: Test LocalGov Drupal Paragraphs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - name: Clone drupal_container
        uses: actions/checkout@v2
        with:
          repository: localgovdrupal/drupal-container
          ref: master

      - name: Create LocalGovDrupal project
        run: composer create-project --stability dev localgovdrupal/localgov-project html

      - name: Grab target branch to test
        run: |
          composer --working-dir=html config repositories.1 vcs git@github.com:${{ github.repository }}.git
          composer --working-dir=html require ${{ github.repository }}:'dev-${{ github.head_ref }} as dev-master'

      - name: Start Docker environment
        run: docker-compose up -d

      - name: Run tests
        run: ./run-tests.sh
        shell: bash
